### ISSUE TITLE
current page template tag doesn't working

### ISSUE THREAD

**Issue by quillcraftsman** [quillcraftsman/lavacactus#3]
In this example: https://github.com/eudicots/Cactus/blob/master/cactus/skeleton/templates/base.html#L35 "current_page" tag has been used to mark an active page.
But it's not working then direct link is used. For example: {% if_current_page 'index.html' 'active' '' %}

**Comment by quillcraftsman** [comment]
Hello, you can just
* "Fork" the project
* do some work locally 
* then make a pull request to the main repository (the "contribute" button if the project is a fork)

**Comment by quillcraftsman** [comment]
I've added https://github.com/quillcraftsman/lavacactus/blob/master/DEVELOPER_GUIDELINES.md this tutorial to easy get start.

**Comment by hind-sagar-biswas** [comment]
Umm, I forked it, setup a venv env, installed requirements and test_requirements.

Now what do I actually run, like how do I see the output... I am new to this, so It'd be great if ya guide me

**Comment by S1wH** [comment]
U can can follow README Super quick tutorial inside this forked repository to see how actually cactus work

**Comment by hind-sagar-biswas** [comment]
Yeah I followed it and on step of `cactus create test-project`

I got:
```
Traceback (most recent call last):
  File "F:\WebNProg\Pythons\cactus\.env\Lib\site-packages\cactus\utils\packaging.py", line 7, in pkg_walk
    cur_dir, dirs, non_dirs = next(os.walk(os.path.join(package, top)))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\WebNProg\Pythons\cactus\.env\Scripts\cactus.exe\__main__.py", line 7, in <module>
  File "F:\WebNProg\Pythons\cactus\.env\Lib\site-packages\cactus\cli.py", line 159, in cli_entrypoint
    main(sys.argv[1:])
  File "F:\WebNProg\Pythons\cactus\.env\Lib\site-packages\cactus\cli.py", line 155, in main
    ns.target(**kwargs)
  File "F:\WebNProg\Pythons\cactus\.env\Lib\site-packages\cactus\cli.py", line 45, in create
    self.bootstrap(path, skeleton)
  File "F:\WebNProg\Pythons\cactus\.env\Lib\site-packages\cactus\bootstrap\__init__.py", line 20, in bootstrap
    bootstrap_from_package(path)
  File "F:\WebNProg\Pythons\cactus\.env\Lib\site-packages\cactus\bootstrap\package.py", line 13, in bootstrap_from_package
    for dir_, sub_dirs, filenames in pkg_walk("cactus", "skeleton"):
RuntimeError: generator raised StopIteration
```

what I did was create a venv .env, in there installed the package the run `cactus create test-project`

**Comment by quillcraftsman** [comment]
You've done all steps properly. 

Looks like you've found a critical bug in new release. I will create a special issue to fix it with main priority.

**Comment by quillcraftsman** [comment]
https://github.com/quillcraftsman/lavacactus/issues/7

**Comment by quillcraftsman** [comment]
@S1wH , fix the bug in new release 1.1.2. The command `cactus create some-name` should work now.
Note:

- To use library we get it from pypi `pip install lava-cactus`
- To develop we clone the project fork and run `make install`. Then after some change run `make reinstall` to check new features.

**Comment by hind-sagar-biswas** [comment]
Okay, so after I updated to the new version, I ran:

1. `cactus create test-project` -> worked
2. `cd test-project` -> worked
3.  Did no changes
4. `cactus build` -> error

Was I supposed to make any changes... Also the error I got:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\Scripts\cactus.exe\__main__.py", line 7, in <module>
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\cli.py", line 162, in cli_entrypoint
    main(sys.argv[1:])
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\cli.py", line 158, in main
    ns.target(**kwargs)
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\cli.py", line 51, in build
    site.build()
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\site.py", line 307, in build
    self.build_with_translation()
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\site.py", line 295, in build_with_translation
    mapper(lambda p: p.build(), self.pages())
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\utils\helpers.py", line 64, in map_apply
    return list(map(fn, iterable))
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\site.py", line 295, in <lambda>
    mapper(lambda p: p.build(), self.pages())
                     ^^^^^^^^^
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\page.py", line 116, in build
    data = self.render()  #TODO: This calls preBuild indirectly. Not great.
           ^^^^^^^^^^^^^
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\page.py", line 107, in render
    context, data = self.site.plugin_manager.preBuildPage(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\plugin\manager.py", line 49, in preBuildPage
    n_args = len(getargspec(plugin.preBuildPage).args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hinds\AppData\Roaming\Python\Python311\site-packages\cactus\utils\internal.py", line 45, in getargspec
    spec = inspect.getargspec(getattr(obj, FUNC_OBJ_ATTR))
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

**Comment by quillcraftsman** [comment]
@hind-sagar-biswas , what python version do you use? Looks like is't python > 3.10 in 3.11 method getargspec was removed.

**Comment by quillcraftsman** [comment]
@hind-sagar-biswas , me be you try to fix this issue https://github.com/quillcraftsman/lavacactus/issues/9? It's just about python 3.11 support. I think it will be useful later.

**Comment by hind-sagar-biswas** [comment]
Yeah I knew the fix but faced other build issues so could not implement
